[package]
name = "regex"
version = "0.1.30"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/regex"
documentation = "http://doc.rust-lang.org/regex"
homepage = "https://github.com/rust-lang/regex"
description = """
An implementation of regular expressions for Rust.
"""

[[test]]
path = "regex_macros/tests/test_dynamic.rs"
name = "all"

[[bench]]
name = "all"
path = "regex_macros/benches/bench_dynamic.rs"
test = false
bench = true

[dev-dependencies]
rand = "0.3"

[features]
pattern = []
