[package]

name = "html5ever_macros"
version = "0.0.0"
authors = [ "The html5ever Project Developers" ]

[lib]

name = "html5ever_macros"
plugin = true

[dependencies]
rustc-serialize = "0"

[dependencies.mac]
git = "https://github.com/reem/rust-mac"
